### ISSUE TITLE
PHP Notice on Widgets editor

### ISSUE THREAD

**Issue by scottsanders** [creativefreedom/freedomtheme#6]
`wp-edit-post` throws an PHP notice on the new widget editor. Removing it removed the notice. Is this needed?

https://github.com/creativefreedom/freedomtheme/blob/6759f008e43be669bc9c4090e4e2051239a83bbb/inc/enqueue.php#L34

**Comment by amhislop** [comment]
@scottsanders - I'm not seeing this in WP 5.8+. Are you still seeing this notice in the editor (/wp-admin/widgets.php)

**Comment by scottsanders** [comment]
It was actually reported by Instance, so I'm not 100% sure.

**Comment by amhislop** [comment]
Ok I can't see it still occurring so I'll close this one off for now and we can reopen it if we come across it again.
